<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\Simulab.Identity.Api\Simulab.Identity.Api.csproj" />
    <ProjectReference Include="..\..\src\Simulab.Api\Simulab.Api.csproj" />
    <ProjectReference Include="..\Simulab.Testing\Simulab.Testing.csproj" />
  </ItemGroup>

</Project>
