// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simulab.Jobs.Persistence;

#nullable disable

namespace Simulab.Jobs.Persistence.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260925171632_AddColumnDescriptions")]
    partial class AddColumnDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jobs")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simulab.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts")
                        .HasComment("How many times a worker has started it. The first attempt makes it 1.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the job was enqueued, in UTC. The worker takes the oldest first. This is not an audit field: the queue is not audited.");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error")
                        .HasComment("The message of the last failure, kept with a failed row. Cut so one bad job cannot fill the table.");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload")
                        .HasComment("The whole input of the job, as JSON. Cleared when the job is given up on: the message is a live link and an address, not evidence.");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after")
                        .HasComment("Not to be run before this instant, in UTC. Set at enqueue and pushed forward by the retry backoff.");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasComment("When the current attempt started, in UTC. A row stuck here is taken again by another worker.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("What the row is doing: 0 waiting for its turn, 1 a worker is running it, 2 every attempt failed. There is no value for success, because a job that succeeds leaves no row.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type")
                        .HasComment("Which handler runs the job. The worker matches it against the handlers registered in the host.");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_jobs_active_created_at")
                        .HasFilter("status IN (0, 1)");

                    b.ToTable("jobs", "jobs", t =>
                        {
                            t.HasComment("Work that must happen but must not make a request wait, such as sending an email. A job that succeeds leaves no row.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
