using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Simulab.Jobs.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddColumnDescriptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterTable(
                name: "jobs",
                schema: "jobs",
                comment: "Work that must happen but must not make a request wait, such as sending an email. A job that succeeds leaves no row.");

            migrationBuilder.AlterColumn<string>(
                name: "type",
                schema: "jobs",
                table: "jobs",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                comment: "Which handler runs the job. The worker matches it against the handlers registered in the host.",
                oldClrType: typeof(string),
                oldType: "character varying(100)",
                oldMaxLength: 100);

            migrationBuilder.AlterColumn<int>(
                name: "status",
                schema: "jobs",
                table: "jobs",
                type: "integer",
                nullable: false,
                comment: "What the row is doing: 0 waiting for its turn, 1 a worker is running it, 2 every attempt failed. There is no value for success, because a job that succeeds leaves no row.",
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "started_at",
                schema: "jobs",
                table: "jobs",
                type: "timestamp with time zone",
                nullable: true,
                comment: "When the current attempt started, in UTC. A row stuck here is taken again by another worker.",
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "run_after",
                schema: "jobs",
                table: "jobs",
                type: "timestamp with time zone",
                nullable: false,
                comment: "Not to be run before this instant, in UTC. Set at enqueue and pushed forward by the retry backoff.",
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<string>(
                name: "payload",
                schema: "jobs",
                table: "jobs",
                type: "text",
                nullable: false,
                comment: "The whole input of the job, as JSON. Cleared when the job is given up on: the message is a live link and an address, not evidence.",
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "last_error",
                schema: "jobs",
                table: "jobs",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: true,
                comment: "The message of the last failure, kept with a failed row. Cut so one bad job cannot fill the table.",
                oldClrType: typeof(string),
                oldType: "character varying(2000)",
                oldMaxLength: 2000,
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "created_at",
                schema: "jobs",
                table: "jobs",
                type: "timestamp with time zone",
                nullable: false,
                comment: "When the job was enqueued, in UTC. The worker takes the oldest first. This is not an audit field: the queue is not audited.",
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<int>(
                name: "attempts",
                schema: "jobs",
                table: "jobs",
                type: "integer",
                nullable: false,
                comment: "How many times a worker has started it. The first attempt makes it 1.",
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<Guid>(
                name: "id",
                schema: "jobs",
                table: "jobs",
                type: "uuid",
                nullable: false,
                comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time.",
                oldClrType: typeof(Guid),
                oldType: "uuid");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterTable(
                name: "jobs",
                schema: "jobs",
                oldComment: "Work that must happen but must not make a request wait, such as sending an email. A job that succeeds leaves no row.");

            migrationBuilder.AlterColumn<string>(
                name: "type",
                schema: "jobs",
                table: "jobs",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(100)",
                oldMaxLength: 100,
                oldComment: "Which handler runs the job. The worker matches it against the handlers registered in the host.");

            migrationBuilder.AlterColumn<int>(
                name: "status",
                schema: "jobs",
                table: "jobs",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldComment: "What the row is doing: 0 waiting for its turn, 1 a worker is running it, 2 every attempt failed. There is no value for success, because a job that succeeds leaves no row.");

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "started_at",
                schema: "jobs",
                table: "jobs",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone",
                oldNullable: true,
                oldComment: "When the current attempt started, in UTC. A row stuck here is taken again by another worker.");

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "run_after",
                schema: "jobs",
                table: "jobs",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone",
                oldComment: "Not to be run before this instant, in UTC. Set at enqueue and pushed forward by the retry backoff.");

            migrationBuilder.AlterColumn<string>(
                name: "payload",
                schema: "jobs",
                table: "jobs",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text",
                oldComment: "The whole input of the job, as JSON. Cleared when the job is given up on: the message is a live link and an address, not evidence.");

            migrationBuilder.AlterColumn<string>(
                name: "last_error",
                schema: "jobs",
                table: "jobs",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(2000)",
                oldMaxLength: 2000,
                oldNullable: true,
                oldComment: "The message of the last failure, kept with a failed row. Cut so one bad job cannot fill the table.");

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "created_at",
                schema: "jobs",
                table: "jobs",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone",
                oldComment: "When the job was enqueued, in UTC. The worker takes the oldest first. This is not an audit field: the queue is not audited.");

            migrationBuilder.AlterColumn<int>(
                name: "attempts",
                schema: "jobs",
                table: "jobs",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldComment: "How many times a worker has started it. The first attempt makes it 1.");

            migrationBuilder.AlterColumn<Guid>(
                name: "id",
                schema: "jobs",
                table: "jobs",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldComment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");
        }
    }
}
