<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Catalog\Simulab.Catalog.Api\Simulab.Catalog.Api.csproj" />
    <ProjectReference Include="..\..\..\..\src\Hosts\Simulab.Api\Simulab.Api.csproj" />
    <ProjectReference Include="..\..\..\Simulab.Testing\Simulab.Testing.csproj" />
  </ItemGroup>

</Project>
