// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simulab.Identity.Infrastructure.Persistence;

#nullable disable

namespace Simulab.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityModuleDbContext))]
    partial class IdentityModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_openiddict_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_openiddict_applications_client_id");

                    b.ToTable("openiddict_applications", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_openiddict_authorizations");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_openiddict_authorizations_application_id_status_subject_type");

                    b.ToTable("openiddict_authorizations", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id")
                        .HasName("pk_openiddict_scopes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_openiddict_scopes_name");

                    b.ToTable("openiddict_scopes", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_openiddict_tokens");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("ix_openiddict_tokens_authorization_id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_openiddict_tokens_reference_id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_openiddict_tokens_application_id_status_subject_type");

                    b.ToTable("openiddict_tokens", "identity");
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.AccountEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address")
                        .HasComment("The address the request came from, long enough for IPv6. Null when it could not be read.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("Method")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method")
                        .HasComment("How it was done, such as Password or Google. Null when the event has no method.");

                    b.Property<string>("Reason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason")
                        .HasComment("Why it failed, such as WrongPassword or LockedOut. Null when nothing failed.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type")
                        .HasComment("What happened, such as SignInSucceeded, PasswordChanged or TwoFactorEnabled.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Whose account it happened to. Null when the attempt named no existing account.");

                    b.HasKey("Id")
                        .HasName("pk_account_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_account_events_created_at");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("ix_account_events_ip_address");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_account_events_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_events_user_id");

                    b.ToTable("account_events", "identity", t =>
                        {
                            t.HasComment("What happened to an account: sign-ins, password changes, two-factor enrolments. A person reads their own recent activity from it, and it is kept when the account is erased, without naming anyone.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasComment("When they accepted, in UTC.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<bool>("DeclaresAdult")
                        .HasColumnType("boolean")
                        .HasColumnName("declares_adult")
                        .HasComment("The person declared they are 18 or older when accepting.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address")
                        .HasComment("The address the acceptance came from, long enough for IPv6. Null when it could not be read.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale")
                        .HasComment("The language the documents were shown in, such as pt-BR: it is what they actually read.");

                    b.Property<string>("PrivacyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("privacy_version")
                        .HasComment("The version of the privacy policy that was shown and accepted.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("terms_version")
                        .HasComment("The version of the terms that was shown and accepted.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Who accepted.");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_consent_records_user_id");

                    b.ToTable("consent_records", "identity", t =>
                        {
                            t.HasComment("Evidence that a person accepted the terms and the privacy policy, with the versions they saw. Legal evidence: erasing an account never takes it along.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at")
                        .HasComment("When the link was spent, in UTC. Null while it is still usable; set once, so it cannot be used twice.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasComment("When the link stops working, in UTC.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash")
                        .HasComment("The hash of the token that travelled in the link. The token itself is never stored, so a copy of this table does not let anyone in.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Whose account the link belongs to.");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", "identity", t =>
                        {
                            t.HasComment("The single-use link that proves an address belongs to the person who signed up. It is spent on the first success and never replayed.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at")
                        .HasComment("When the link was spent, in UTC. Null while it is still usable; set once, so it cannot be used twice.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasComment("When the link stops working, in UTC.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash")
                        .HasComment("The hash of the token that travelled in the link. The token itself is never stored, so a copy of this table does not let anyone in.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Whose account the link belongs to.");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", "identity", t =>
                        {
                            t.HasComment("The single-use link that lets someone set a new password without knowing the old one. It is spent on the first success and never replayed.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("The permission name and the key of the row, such as catalog.manage. The part before the first dot is the module that declares it.");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasComment("What the permission allows, shown to an admin choosing permissions for a role.");

                    b.HasKey("Name")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "identity", t =>
                        {
                            t.HasComment("Everything a role can be allowed to do. Each module declares its own names and Identity seeds the union of them.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasComment("Changes on every save, so two admins editing the same role at once cannot overwrite each other silently.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system")
                        .HasComment("True for a role Simulab seeds and depends on, such as Admin: it cannot be renamed or deleted.");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .HasComment("The role's name, as it is shown and as permissions are granted to it.");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name")
                        .HasComment("The name upper-cased, which is what the unique index compares.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("roles", "identity", t =>
                        {
                            t.HasComment("A named set of permissions given to people, such as Student, Curator or Admin. A deleted role keeps its name taken.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.RoleChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action")
                        .HasComment("What was done: RoleCreated, RoleUpdated, RoleDeleted or UserRolesChanged.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("NameAfter")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_after")
                        .HasComment("The name after a rename. Null for any other action.");

                    b.Property<string>("NameBefore")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_before")
                        .HasComment("The name before a rename. Null for any other action.");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("The role that changed. Null when the change was about a person's roles rather than one role.");

                    b.PrimitiveCollection<List<Guid>>("RoleIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("role_ids")
                        .HasComment("Every role the change touched, so a search by role finds it whichever action it was.");

                    b.Property<string>("RoleName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("role_name")
                        .HasComment("The role's name when the change happened, kept so the trail still reads after the role is deleted.");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id")
                        .HasComment("Whose roles changed. Null when the change was about the role itself.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.HasKey("Id")
                        .HasName("pk_role_changes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_role_changes_created_at");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_role_changes_created_by");

                    b.HasIndex("RoleIds")
                        .HasDatabaseName("ix_role_changes_role_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RoleIds"), "gin");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_role_changes_target_user_id");

                    b.ToTable("role_changes", "identity", t =>
                        {
                            t.HasComment("The trail of what was done to roles and to who holds them: created, renamed, deleted, granted, revoked. Read by an admin auditing access.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("The role the permission is granted to.");

                    b.Property<string>("PermissionName")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_name")
                        .HasComment("The permission that is granted.");

                    b.HasKey("RoleId", "PermissionName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionName")
                        .HasDatabaseName("ix_role_permissions_permission_name");

                    b.ToTable("role_permissions", "identity", t =>
                        {
                            t.HasComment("Which permissions a role has. A row is the grant itself; removing it takes the permission away.");
                        });
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count")
                        .HasComment("Failed sign-in attempts since the last success. It reaches the limit and locks the account, and a success clears it.");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasComment("Changes on every save, so two people editing the same account at once cannot overwrite each other silently.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email")
                        .HasComment("The address the person signs in with and receives mail at.");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasComment("True once the person followed the verification link. Sign-in is refused until then.");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at")
                        .HasComment("When the person followed the verification link, in UTC. Null while the address is unverified.");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name")
                        .HasComment("The name the person gave, shown in the app. Cleared when the account is erased.");

                    b.Property<bool>("IsAdultDeclared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adult_declared")
                        .HasComment("The person declared at sign-up that they are 18 or older. Simulab takes the declaration; it does not check an age.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled")
                        .HasComment("True when this account can be locked out after failed sign-ins. True for everyone.");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end")
                        .HasComment("The account refuses sign-in until this instant, after too many failed attempts. Null when it is not locked.");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password")
                        .HasComment("True when the person must pick a new password before signing in for real. Set on the seeded administrator and cleared by any password set.");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email")
                        .HasComment("The address upper-cased, which is what the unique index compares: one account per address.");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_user_name")
                        .HasComment("The sign-in name upper-cased, which is what the unique index compares.");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasComment("The password, hashed by ASP.NET Identity. The password itself is never stored and cannot be recovered from this.");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number")
                        .HasComment("Not used by Simulab: no feature collects a phone number. The column belongs to ASP.NET Identity.");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed")
                        .HasComment("Not used by Simulab, like the phone number itself.");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_language")
                        .HasComment("The language the app and its emails use for this person, such as pt-BR. It is the first source of the culture, before the cookie and the browser.");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp")
                        .HasComment("Changes whenever the credentials change. Every open session that does not carry the current value is rejected, which is how a password change signs other devices out.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("Where the account stands: Pending, Active or Erased.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("TotpEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enabled_at")
                        .HasComment("When two-factor enrolment finished, in UTC. Null while it is off.");

                    b.Property<long?>("TotpLastAcceptedStep")
                        .HasColumnType("bigint")
                        .HasColumnName("totp_last_accepted_step")
                        .HasComment("The last time step accepted by two-factor. A code from that step or earlier is refused, so one code cannot be used twice.");

                    b.Property<string>("TotpSecretEncrypted")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("totp_secret_encrypted")
                        .HasComment("The two-factor secret, encrypted with the app's key. Losing that key makes every enrolment unusable.");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled")
                        .HasComment("True when the person finished enrolling in two-factor sign-in.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<string>("UserName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("user_name")
                        .HasComment("The sign-in name. Simulab signs in by email, so it holds the same address.");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_tenant_normalized_email");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedEmail"), false);

                    b.HasIndex("TenantId", "NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_tenant_normalized_user_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedUserName"), false);

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasComment("A person with an account. Erasing an account anonymizes this row rather than removing it, so their attempts stay countable without naming anyone.");
                        });
                });

            modelBuilder.Entity("Simulab.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts")
                        .HasComment("How many times a worker has started it. The first attempt makes it 1.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the job was enqueued, in UTC. The worker takes the oldest first. This is not an audit field: the queue is not audited.");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error")
                        .HasComment("The message of the last failure, kept with a failed row. Cut so one bad job cannot fill the table.");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload")
                        .HasComment("The whole input of the job, as JSON. Cleared when the job is given up on: the message is a live link and an address, not evidence.");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after")
                        .HasComment("Not to be run before this instant, in UTC. Set at enqueue and pushed forward by the retry backoff.");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasComment("When the current attempt started, in UTC. A row stuck here is taken again by another worker.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("What the row is doing: 0 waiting for its turn, 1 a worker is running it, 2 every attempt failed. There is no value for success, because a job that succeeds leaves no row.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type")
                        .HasComment("Which handler runs the job. The worker matches it against the handlers registered in the host.");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_jobs_active_created_at")
                        .HasFilter("status IN (0, 1)");

                    b.ToTable("jobs", "jobs", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasComment("Work that must happen but must not make a request wait, such as sending an email. A job that succeeds leaves no row.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_openiddict_authorizations_openiddict_applications_applicati");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_openiddict_tokens_openiddict_applications_application_id");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_openiddict_tokens_openiddict_authorizations_authorization_id");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_users_user_id");
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.RoleChange", b =>
                {
                    b.OwnsMany("Simulab.Identity.Domain.Entities.RoleChangeItem", "Added", b1 =>
                        {
                            b1.Property<Guid>("RoleChangeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("RoleChangeId", "__synthesizedOrdinal")
                                .HasName("pk_role_changes");

                            b1.ToTable("role_changes", "identity");

                            b1
                                .ToJson("added")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoleChangeId")
                                .HasConstraintName("fk_role_changes_role_changes_role_change_id");
                        });

                    b.OwnsMany("Simulab.Identity.Domain.Entities.RoleChangeItem", "Removed", b1 =>
                        {
                            b1.Property<Guid>("RoleChangeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("RoleChangeId", "__synthesizedOrdinal")
                                .HasName("pk_role_changes");

                            b1.ToTable("role_changes", "identity");

                            b1
                                .ToJson("removed")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoleChangeId")
                                .HasConstraintName("fk_role_changes_role_changes_role_change_id");
                        });

                    b.Navigation("Added");

                    b.Navigation("Removed");
                });

            modelBuilder.Entity("Simulab.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Simulab.Identity.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_name");

                    b.HasOne("Simulab.Identity.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
