// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simulab.Ai.Persistence;

#nullable disable

namespace Simulab.Ai.Persistence.Migrations
{
    [DbContext(typeof(AiDbContext))]
    partial class AiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simulab.Ai.AiCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cost_usd")
                        .HasComment("What the call cost in US dollars: the tokens multiplied by the two prices on this row.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms")
                        .HasComment("How long the call took, in milliseconds, measured around the request.");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code")
                        .HasComment("Why the call failed, as a stable code such as ai.call_failed. Null when it succeeded.");

                    b.Property<decimal>("InputPricePerMillion")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("input_price_per_million")
                        .HasComment("US dollars per million input tokens, as configured when the call was made. Kept on the row so a later price change never rewrites the past.");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens")
                        .HasComment("Tokens the request spent, as the answer reports them. Zero on a failed call, where none are known.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model")
                        .HasComment("The model that was called, as the provider names it.");

                    b.Property<decimal>("OutputPricePerMillion")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("output_price_per_million")
                        .HasComment("US dollars per million output tokens, as configured when the call was made.");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens")
                        .HasComment("Tokens the answer spent, as the answer reports them. Zero on a failed call, where none are known.");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose")
                        .HasComment("What the call was for, such as diagnostics. Cost can be read per purpose, and a purpose can be sent to another model from configuration.");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasComment("When the call left the app, in UTC. The monthly quota counts from the first day of the calendar month.");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded")
                        .HasComment("False when the model answered with an error or could not be reached. Only successful calls count against the monthly quota.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Who the call is charged to. Every call belongs to a signed-in user.");

                    b.HasKey("Id")
                        .HasName("pk_ai_calls");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_ai_calls_user_started_at");

                    b.ToTable("ai_calls", "ai", t =>
                        {
                            t.HasComment("One call that reached the model, answered or failed. A call the gateway refused before it left the app is not here: nothing was spent.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
