using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Simulab.Catalog.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddSubjectTaxonomy : Migration
    {
        private static readonly DateTimeOffset SeededAt = new(2026, 10, 4, 12, 0, 0, TimeSpan.Zero);

        private static readonly Guid[] AreaIds =
        [
            new("0198f370-0005-7000-8000-000000000001"),
            new("0198f370-0005-7000-8000-000000000002"),
            new("0198f370-0005-7000-8000-000000000003"),
            new("0198f370-0005-7000-8000-000000000004"),
            new("0198f370-0005-7000-8000-000000000005"),
            new("0198f370-0005-7000-8000-000000000006"),
            new("0198f370-0005-7000-8000-000000000007"),
            new("0198f370-0005-7000-8000-000000000008"),
            new("0198f370-0005-7000-8000-000000000009"),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "areas",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time."),
                    code = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false, comment: "Stable code the UI names the area by, such as Law; the resource key is Area.<Code>."),
                    display_order = table.Column<int>(type: "integer", nullable: false, comment: "Where the area sits in the list, starting at 1."),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant."),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "When the row was created, in UTC. Filled by the audit interceptor; never set by hand."),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who created the row. Null when no one was signed in, as in a sign-up or a background job."),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was last changed, in UTC. Null while it has never been changed."),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who last changed the row. Null while it has never been changed, or when no one was signed in."),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, comment: "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones."),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was deleted, in UTC. Null while it is not deleted."),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who deleted the row. Null while it is not deleted, or when no one was signed in.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_areas", x => x.id);
                },
                comment: "The fixed list of areas a subject may belong to, seeded by a migration; its names live in the resource files.");

            migrationBuilder.CreateTable(
                name: "subjects",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time."),
                    name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false, comment: "The name as typed; content, so it is not translated."),
                    normalized_name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false, comment: "The name without case or accents, which is what the unique index compares."),
                    area_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The area the subject belongs to; empty when it has none."),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant."),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "When the row was created, in UTC. Filled by the audit interceptor; never set by hand."),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who created the row. Null when no one was signed in, as in a sign-up or a background job."),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was last changed, in UTC. Null while it has never been changed."),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who last changed the row. Null while it has never been changed, or when no one was signed in."),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, comment: "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones."),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was deleted, in UTC. Null while it is not deleted."),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who deleted the row. Null while it is not deleted, or when no one was signed in.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_subjects", x => x.id);
                    table.ForeignKey(
                        name: "fk_subjects_area",
                        column: x => x.area_id,
                        principalSchema: "catalog",
                        principalTable: "areas",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "A subject of the canonical taxonomy, such as Portuguese or Constitutional Law, that topics hang under.");

            migrationBuilder.CreateTable(
                name: "topics",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time."),
                    subject_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "The subject the topic sits under; an edit may move it to another."),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false, comment: "The name as typed; content, so it is not translated."),
                    normalized_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false, comment: "The name without case or accents, which is what the unique index compares."),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant."),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "When the row was created, in UTC. Filled by the audit interceptor; never set by hand."),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who created the row. Null when no one was signed in, as in a sign-up or a background job."),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was last changed, in UTC. Null while it has never been changed."),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who last changed the row. Null while it has never been changed, or when no one was signed in."),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, comment: "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones."),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was deleted, in UTC. Null while it is not deleted."),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who deleted the row. Null while it is not deleted, or when no one was signed in.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_topics", x => x.id);
                    table.ForeignKey(
                        name: "fk_topics_subject",
                        column: x => x.subject_id,
                        principalSchema: "catalog",
                        principalTable: "subjects",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "A topic under a subject, such as Crase under Portuguese.");

            migrationBuilder.CreateIndex(
                name: "ux_areas_tenant_code",
                schema: "catalog",
                table: "areas",
                columns: new[] { "tenant_id", "code" },
                unique: true)
                .Annotation("Npgsql:NullsDistinct", false);

            migrationBuilder.CreateIndex(
                name: "ix_subjects_area",
                schema: "catalog",
                table: "subjects",
                column: "area_id");

            migrationBuilder.CreateIndex(
                name: "ux_subjects_tenant_normalized_name",
                schema: "catalog",
                table: "subjects",
                columns: new[] { "tenant_id", "normalized_name" },
                unique: true)
                .Annotation("Npgsql:NullsDistinct", false);

            migrationBuilder.CreateIndex(
                name: "ix_topics_subject",
                schema: "catalog",
                table: "topics",
                column: "subject_id");

            migrationBuilder.CreateIndex(
                name: "ux_topics_tenant_subject_normalized_name",
                schema: "catalog",
                table: "topics",
                columns: new[] { "tenant_id", "subject_id", "normalized_name" },
                unique: true)
                .Annotation("Npgsql:NullsDistinct", false);

            // F-79 BR1: the nine areas, in display order. Frozen literals with fixed ids, as in the F-37 seed:
            // a later edit to the code never changes what this migration wrote. The names are not stored; the
            // UI reads the resource key Area.<code>. A new area is a new migration plus three resource entries.
            string[] areaCodes =
            [
                "Languages",
                "Mathematics",
                "LogicalReasoning",
                "NaturalSciences",
                "HumanSciences",
                "Law",
                "InformationTechnology",
                "Administration",
                "SpecificKnowledge",
            ];

            for (var i = 0; i < areaCodes.Length; i++)
            {
                migrationBuilder.InsertData(
                    schema: "catalog",
                    table: "areas",
                    columns: ["id", "code", "display_order", "created_at", "is_deleted"],
                    values: new object[]
                    {
                        AreaIds[i], areaCodes[i], i + 1, SeededAt, false,
                    });
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "topics",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "subjects",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "areas",
                schema: "catalog");
        }
    }
}
