using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Simulab.Catalog.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddNoticeSubjects : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "notice_subjects",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time."),
                    exam_edition_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "The edition whose notice names the subject. Fixed when the row is created."),
                    group_label = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true, comment: "How the notice groups the subject, as typed. Empty when the notice does not group."),
                    normalized_group = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, comment: "The group without case or accents, empty when there is none. The unique index compares it."),
                    label = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false, comment: "The subject as the notice names it."),
                    normalized_label = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false, comment: "The label without case or accents. The unique index compares it."),
                    question_count = table.Column<int>(type: "integer", nullable: true, comment: "How many questions the notice states for the subject, 1 to 500. Empty when it does not say."),
                    display_order = table.Column<int>(type: "integer", nullable: false, comment: "Where the row sits inside its edition. Rows of one group are consecutive; every write renumbers from 1."),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant."),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "When the row was created, in UTC. Filled by the audit interceptor; never set by hand."),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who created the row. Null when no one was signed in, as in a sign-up or a background job."),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was last changed, in UTC. Null while it has never been changed."),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who last changed the row. Null while it has never been changed, or when no one was signed in."),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, comment: "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones."),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was deleted, in UTC. Null while it is not deleted."),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who deleted the row. Null while it is not deleted, or when no one was signed in.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_notice_subjects", x => x.id);
                    table.ForeignKey(
                        name: "fk_notice_subjects_exam_edition",
                        column: x => x.exam_edition_id,
                        principalSchema: "catalog",
                        principalTable: "exam_editions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "A subject as one edition's notice names and groups it, with the number of questions the notice states.");

            migrationBuilder.CreateIndex(
                name: "ix_notice_subjects_edition_order",
                schema: "catalog",
                table: "notice_subjects",
                columns: new[] { "exam_edition_id", "display_order" });

            migrationBuilder.CreateIndex(
                name: "ux_notice_subjects_tenant_edition_group_label",
                schema: "catalog",
                table: "notice_subjects",
                columns: new[] { "tenant_id", "exam_edition_id", "normalized_group", "normalized_label" },
                unique: true,
                filter: "is_deleted = false")
                .Annotation("Npgsql:NullsDistinct", false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "notice_subjects",
                schema: "catalog");
        }
    }
}
