using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Simulab.Catalog.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddNoticeSubjectMappings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "notice_subject_mappings",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time."),
                    notice_subject_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "The notice subject whose mapping this entry belongs to."),
                    subject_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The canonical subject covered whole. Empty when the entry is a topic."),
                    topic_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The canonical topic covered. Empty when the entry is a whole subject. Follows the topic when it moves to another subject."),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant."),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "When the row was created, in UTC. Filled by the audit interceptor; never set by hand."),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who created the row. Null when no one was signed in, as in a sign-up or a background job."),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was last changed, in UTC. Null while it has never been changed."),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who last changed the row. Null while it has never been changed, or when no one was signed in."),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, comment: "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones."),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was deleted, in UTC. Null while it is not deleted."),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who deleted the row. Null while it is not deleted, or when no one was signed in.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_notice_subject_mappings", x => x.id);
                    table.CheckConstraint("ck_notice_subject_mappings_one_target", "num_nonnulls(subject_id, topic_id) = 1");
                    table.ForeignKey(
                        name: "fk_notice_subject_mappings_notice_subject",
                        column: x => x.notice_subject_id,
                        principalSchema: "catalog",
                        principalTable: "notice_subjects",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_notice_subject_mappings_subject",
                        column: x => x.subject_id,
                        principalSchema: "catalog",
                        principalTable: "subjects",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_notice_subject_mappings_topic",
                        column: x => x.topic_id,
                        principalSchema: "catalog",
                        principalTable: "topics",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "One canonical subject or topic that a notice subject covers.");

            migrationBuilder.CreateIndex(
                name: "ix_notice_subject_mappings_notice_subject",
                schema: "catalog",
                table: "notice_subject_mappings",
                column: "notice_subject_id");

            migrationBuilder.CreateIndex(
                name: "ix_notice_subject_mappings_subject",
                schema: "catalog",
                table: "notice_subject_mappings",
                column: "subject_id");

            migrationBuilder.CreateIndex(
                name: "ix_notice_subject_mappings_topic",
                schema: "catalog",
                table: "notice_subject_mappings",
                column: "topic_id");

            migrationBuilder.CreateIndex(
                name: "ux_notice_subject_mappings_tenant_notice_subject_target",
                schema: "catalog",
                table: "notice_subject_mappings",
                columns: new[] { "tenant_id", "notice_subject_id", "subject_id", "topic_id" },
                unique: true,
                filter: "is_deleted = false")
                .Annotation("Npgsql:NullsDistinct", false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "notice_subject_mappings",
                schema: "catalog");
        }
    }
}
