// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simulab.Catalog.Infrastructure.Persistence;

#nullable disable

namespace Simulab.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogModuleDbContext))]
    [Migration("20260929095356_FixEnumColumnDescriptions")]
    partial class FixEnumColumnDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simulab.Catalog.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("assessment_type")
                        .HasComment("What kind of assessment it is: PublicServiceExam, Certification, UniversityEntranceExam or Enem.");

                    b.Property<string>("ContentLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("content_language")
                        .HasComment("The language the questions are written in, such as pt-BR. Exam content is never translated.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<Guid>("IssuingAuthorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_authority_id")
                        .HasComment("The body that publishes this exam's notices.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .HasComment("The exam's name, unique inside its issuing authority.");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name")
                        .HasComment("The name without case or accents, which is what the unique index compares.");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scope")
                        .HasComment("How far the exam reaches: National, State or Municipal.");

                    b.Property<string>("ScopeDetail")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("scope_detail")
                        .HasComment("Which state or city the scope means, when it is not national.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("IssuingAuthorityId")
                        .HasDatabaseName("ix_exams_issuing_authority");

                    b.HasIndex("TenantId", "IssuingAuthorityId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_exams_tenant_authority_normalized_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "IssuingAuthorityId", "NormalizedName"), false);

                    b.ToTable("exams", "catalog", t =>
                        {
                            t.HasComment("A recurring assessment an issuing authority runs, such as a competitive exam for a job or a certification. Its editions are the papers actually applied.");
                        });
                });

            modelBuilder.Entity("Simulab.Catalog.Domain.Entities.ExamEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<DateOnly?>("AppliedOn")
                        .HasColumnType("date")
                        .HasColumnName("applied_on")
                        .HasComment("The day the paper was applied. Optional, also to publish.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id")
                        .HasComment("The exam this paper belongs to. Fixed when the edition is created.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("NormalizedPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_position")
                        .HasComment("The position without case or accents, empty when there is none. The unique index compares it.");

                    b.Property<string>("NoticeReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notice_reference")
                        .HasComment("How the notice names itself, such as Edital nº 01/2026. Editions cut from one notice share it.");

                    b.Property<string>("NoticeUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("notice_url")
                        .HasComment("The official address of the notice, an absolute http or https URL.");

                    b.Property<int>("NoticeYear")
                        .HasColumnType("integer")
                        .HasColumnName("notice_year")
                        .HasComment("The year of the notice, from 1990 to next year.");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id")
                        .HasComment("The exam board that applied the paper, as the notice names it.");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position")
                        .HasComment("The job the paper selects for. Empty for ENEM, entrance exams and certifications.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status")
                        .HasComment("Who can see the edition: Draft or Published.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.HasKey("Id")
                        .HasName("pk_exam_editions");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_editions_exam");

                    b.HasIndex("OrganizerId", "NoticeYear")
                        .HasDatabaseName("ix_exam_editions_organizer_year");

                    b.HasIndex("TenantId", "ExamId", "NoticeYear", "NormalizedPosition", "OrganizerId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_editions_tenant_exam_year_position_organizer");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "ExamId", "NoticeYear", "NormalizedPosition", "OrganizerId"), false);

                    b.ToTable("exam_editions", "catalog", t =>
                        {
                            t.HasComment("One paper actually applied for an exam: its notice year, the job it selects for, the board that applied it and whether students can see it.");
                        });
                });

            modelBuilder.Entity("Simulab.Catalog.Domain.Entities.IssuingAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acronym")
                        .HasComment("Short name people search by, such as TRF1 or INSS.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasComment("Free notes about the body, shown to whoever curates the catalog.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name")
                        .HasComment("Full name, as the notice writes it.");

                    b.Property<string>("NormalizedAcronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("normalized_acronym")
                        .HasComment("The acronym without case or accents, which is what the unique index compares.");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name")
                        .HasComment("The name without case or accents, which is what the unique index compares.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website")
                        .HasComment("The body's own address, where its notices are published.");

                    b.HasKey("Id")
                        .HasName("pk_issuing_authorities");

                    b.HasIndex("TenantId", "NormalizedAcronym")
                        .IsUnique()
                        .HasDatabaseName("ux_issuing_authorities_tenant_normalized_acronym");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedAcronym"), false);

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_issuing_authorities_tenant_normalized_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedName"), false);

                    b.ToTable("issuing_authorities", "catalog", t =>
                        {
                            t.HasComment("The body that publishes a notice and contracts an organizer to run the exam: a ministry, a court, a city hall.");
                        });
                });

            modelBuilder.Entity("Simulab.Catalog.Domain.Entities.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Identifier of the row, a UUID v7: generated by the app, ordered by creation time.");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acronym")
                        .HasComment("Short name people search by, such as CEBRASPE or FGV.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When the row was created, in UTC. Filled by the audit interceptor; never set by hand.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasComment("Who created the row. Null when no one was signed in, as in a sign-up or a background job.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the row was deleted, in UTC. Null while it is not deleted.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the row. Null while it is not deleted, or when no one was signed in.");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasComment("Free notes about the organizer, shown to whoever curates the catalog.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind")
                        .HasComment("What kind of organizer it is: ExamBoard, CertifyingBody or University.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name")
                        .HasComment("Full name, as the organizer writes it.");

                    b.Property<string>("NormalizedAcronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("normalized_acronym")
                        .HasComment("The acronym without case or accents, which is what the unique index compares.");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name")
                        .HasComment("The name without case or accents, which is what the unique index compares.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When the row was last changed, in UTC. Null while it has never been changed.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasComment("Who last changed the row. Null while it has never been changed, or when no one was signed in.");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website")
                        .HasComment("The organizer's own address, where its notices are published.");

                    b.HasKey("Id")
                        .HasName("pk_organizers");

                    b.HasIndex("TenantId", "NormalizedAcronym")
                        .IsUnique()
                        .HasDatabaseName("ux_organizers_tenant_normalized_acronym");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedAcronym"), false);

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_organizers_tenant_normalized_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedName"), false);

                    b.ToTable("organizers", "catalog", t =>
                        {
                            t.HasComment("Who runs an assessment: an exam board, a certifying body or a university. An exam belongs to one of them.");
                        });
                });

            modelBuilder.Entity("Simulab.Catalog.Domain.Entities.Exam", b =>
                {
                    b.HasOne("Simulab.Catalog.Domain.Entities.IssuingAuthority", null)
                        .WithMany()
                        .HasForeignKey("IssuingAuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exams_issuing_authority");
                });

            modelBuilder.Entity("Simulab.Catalog.Domain.Entities.ExamEdition", b =>
                {
                    b.HasOne("Simulab.Catalog.Domain.Entities.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_editions_exam");

                    b.HasOne("Simulab.Catalog.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_editions_organizer");
                });
#pragma warning restore 612, 618
        }
    }
}
