using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Simulab.Catalog.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddExamEditions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "exam_editions",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Identifier of the row, a UUID v7: generated by the app, ordered by creation time."),
                    exam_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "The exam this paper belongs to. Fixed when the edition is created."),
                    organizer_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "The exam board that applied the paper, as the notice names it."),
                    notice_year = table.Column<int>(type: "integer", nullable: false, comment: "The year of the notice, from 1990 to next year."),
                    position = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true, comment: "The job the paper selects for. Empty for ENEM, entrance exams and certifications."),
                    normalized_position = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false, comment: "The position without case or accents, empty when there is none. The unique index compares it."),
                    notice_reference = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true, comment: "How the notice names itself, such as Edital nº 01/2026. Editions cut from one notice share it."),
                    notice_url = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: true, comment: "The official address of the notice, an absolute http or https URL."),
                    applied_on = table.Column<DateOnly>(type: "date", nullable: true, comment: "The day the paper was applied. Optional, also to publish."),
                    status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false, comment: "Who can see the edition: Draft or Published."),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant."),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "When the row was created, in UTC. Filled by the audit interceptor; never set by hand."),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who created the row. Null when no one was signed in, as in a sign-up or a background job."),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was last changed, in UTC. Null while it has never been changed."),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who last changed the row. Null while it has never been changed, or when no one was signed in."),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, comment: "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones."),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "When the row was deleted, in UTC. Null while it is not deleted."),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true, comment: "Who deleted the row. Null while it is not deleted, or when no one was signed in.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_exam_editions", x => x.id);
                    table.ForeignKey(
                        name: "fk_exam_editions_exam",
                        column: x => x.exam_id,
                        principalSchema: "catalog",
                        principalTable: "exams",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_exam_editions_organizer",
                        column: x => x.organizer_id,
                        principalSchema: "catalog",
                        principalTable: "organizers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "One paper actually applied for an exam: its notice year, the job it selects for, the board that applied it and whether students can see it.");

            migrationBuilder.CreateIndex(
                name: "ix_exam_editions_exam",
                schema: "catalog",
                table: "exam_editions",
                column: "exam_id");

            migrationBuilder.CreateIndex(
                name: "ix_exam_editions_organizer_year",
                schema: "catalog",
                table: "exam_editions",
                columns: new[] { "organizer_id", "notice_year" });

            migrationBuilder.CreateIndex(
                name: "ux_exam_editions_tenant_exam_year_position_organizer",
                schema: "catalog",
                table: "exam_editions",
                columns: new[] { "tenant_id", "exam_id", "notice_year", "normalized_position", "organizer_id" },
                unique: true)
                .Annotation("Npgsql:NullsDistinct", false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "exam_editions",
                schema: "catalog");
        }
    }
}
