<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Simulab.Email\Simulab.Email.csproj" />
    <ProjectReference Include="..\..\src\Simulab.SharedKernel\Simulab.SharedKernel.csproj" />
  </ItemGroup>

</Project>
