<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Hosts\Simulab.Web\Simulab.Web.csproj" />
    <ProjectReference Include="..\..\Simulab.Testing\Simulab.Testing.csproj" />
  </ItemGroup>

</Project>
