<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulab.SharedKernel\Simulab.SharedKernel.csproj" />
  </ItemGroup>

</Project>
