using Simulab.SharedKernel.Entities;

namespace Simulab.Persistence.Conventions;

/// <summary>
/// What the columns every entity repeats mean (F-24, BR3). They are written once here and applied by
/// <see cref="StandardColumnCommentConvention"/>, because about 190 of the 272 column rows of the data
/// dictionary are these nine and a copy per configuration would drift.
/// </summary>
/// <remarks>
/// A configuration that says something truer for its own table wins: an explicit <c>HasComment</c> is
/// <c>ConfigurationSource.Explicit</c> and a convention never overwrites it. `jobs.created_at` is the
/// case that needs it — there it is when the job was enqueued, not when an audit trail recorded a row.
/// </remarks>
public static class StandardColumnComments
{
    /// <summary>The surrogate key.</summary>
    public const string Id = "Identifier of the row, a UUID v7: generated by the app, ordered by creation time.";

    /// <summary>Carried by <see cref="TenantEntity"/>.</summary>
    public const string TenantId = "The institution the row belongs to. Null means global data or an individual account, which is every row while multi-tenancy is dormant.";

    /// <summary>Carried by <see cref="IAuditableEntity"/>.</summary>
    public const string CreatedAt = "When the row was created, in UTC. Filled by the audit interceptor; never set by hand.";

    /// <summary>Carried by <see cref="IAuditableEntity"/>.</summary>
    public const string CreatedBy = "Who created the row. Null when no one was signed in, as in a sign-up or a background job.";

    /// <summary>Carried by <see cref="IAuditableEntity"/>.</summary>
    public const string UpdatedAt = "When the row was last changed, in UTC. Null while it has never been changed.";

    /// <summary>Carried by <see cref="IAuditableEntity"/>.</summary>
    public const string UpdatedBy = "Who last changed the row. Null while it has never been changed, or when no one was signed in.";

    /// <summary>Carried by <see cref="ISoftDeletableEntity"/>.</summary>
    public const string IsDeleted = "True once the row was deleted. Rows are never removed; a global query filter hides the deleted ones.";

    /// <summary>Carried by <see cref="ISoftDeletableEntity"/>.</summary>
    public const string DeletedAt = "When the row was deleted, in UTC. Null while it is not deleted.";

    /// <summary>Carried by <see cref="ISoftDeletableEntity"/>.</summary>
    public const string DeletedBy = "Who deleted the row. Null while it is not deleted, or when no one was signed in.";

    /// <summary>The audit columns, by the property name that carries them.</summary>
    public static readonly IReadOnlyDictionary<string, string> Auditable = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [nameof(IAuditableEntity.CreatedAt)] = CreatedAt,
        [nameof(IAuditableEntity.CreatedBy)] = CreatedBy,
        [nameof(IAuditableEntity.UpdatedAt)] = UpdatedAt,
        [nameof(IAuditableEntity.UpdatedBy)] = UpdatedBy
    };

    /// <summary>The soft-delete columns, by the property name that carries them.</summary>
    public static readonly IReadOnlyDictionary<string, string> SoftDeletable = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [nameof(ISoftDeletableEntity.IsDeleted)] = IsDeleted,
        [nameof(ISoftDeletableEntity.DeletedAt)] = DeletedAt,
        [nameof(ISoftDeletableEntity.DeletedBy)] = DeletedBy
    };
}
